Repository badgerloop-software/pod, pull requests merged in 2019-02, with the labels that each got.

#24 Dashboard code cleanup
  dashboard/.gitignore
  dashboard/README.md
  dashboard/app.js
  dashboard/constants.js
  dashboard/database.js
  dashboard/index.html
  dashboard/public/images/settings.png
  dashboard/public/javascripts/DataInterfacing.js
  dashboard/public/javascripts/chartHandling.js
  dashboard/public/javascripts/communication.js
  dashboard/public/javascripts/dropdown.js
  dashboard/public/javascripts/focusClone.js
  dashboard/public/javascripts/generateBlankChart.js
  dashboard/public/javascripts/generateLineChart.js
  dashboard/public/javascripts/getData.js
  dashboard/public/javascripts/handler.js
  dashboard/public/javascripts/tableSearch.js
  dashboard/public/javascripts/tables.js
  dashboard/public/stylesheets/fonts.css
  dashboard/server.js
  dashboard/testPodServer.js
Labels: enhancement

#46 Middleware restructure
  Makefile
  README.md
  embedded/README.md
  embedded/makefile
  middleware/README.md
  middleware/command-recv/README.md
  middleware/command-recv/example/Makefile
  middleware/examples/LV_DataLoop_test.cpp
  middleware/examples/LV_TCP_test.cpp
  middleware/include/HVTCPSocket.h
  middleware/include/HVTelemetry_Loop.h
  middleware/include/LVTCPSocket.h
  middleware/include/LVTelemetry_Loop.h
  middleware/include/PracticalSocket.h
  middleware/include/jsonlib/allocators.h
  middleware/include/jsonlib/cursorstreamwrapper.h
  middleware/include/jsonlib/document.h
  middleware/include/jsonlib/encodedstream.h
  middleware/include/jsonlib/encodings.h
  middleware/include/jsonlib/error/en.h
  middleware/include/jsonlib/error/error.h
  middleware/include/jsonlib/filereadstream.h
  middleware/include/jsonlib/filewritestream.h
  middleware/include/jsonlib/fwd.h
  middleware/include/jsonlib/internal/biginteger.h
  middleware/include/jsonlib/internal/diyfp.h
  middleware/include/jsonlib/internal/dtoa.h
  middleware/include/jsonlib/internal/ieee754.h
  middleware/include/jsonlib/internal/itoa.h
  middleware/include/jsonlib/internal/meta.h
  middleware/include/jsonlib/internal/pow10.h
  middleware/include/jsonlib/internal/regex.h
  middleware/include/jsonlib/internal/stack.h
  middleware/include/jsonlib/internal/strfunc.h
  middleware/include/jsonlib/internal/strtod.h
  middleware/include/jsonlib/internal/swap.h
  middleware/include/jsonlib/istreamwrapper.h
  middleware/include/jsonlib/memorybuffer.h
  middleware/include/jsonlib/memorystream.h
  middleware/include/jsonlib/msinttypes/inttypes.h
  middleware/include/jsonlib/msinttypes/stdint.h
  middleware/include/jsonlib/ostreamwrapper.h
  middleware/include/jsonlib/pointer.h
  middleware/include/jsonlib/prettywriter.h
  middleware/include/jsonlib/rapidjson.h
  middleware/include/jsonlib/reader.h
  middleware/include/jsonlib/schema.h
  middleware/include/jsonlib/stream.h
  middleware/include/jsonlib/stringbuffer.h
  middleware/include/jsonlib/writer.h
  middleware/src/HVTCPSocket.cpp
  middleware/src/HVTelemetry_Loop.cpp
  middleware/src/LVTCPSocket.cpp
  middleware/src/LVTelemetry_Loop.cpp
  middleware/src/PracticalSocket.cpp
  middleware/telemetry-loop/README.md
  middleware/telemetry-loop/example/Makefile
Labels: Controls

#51 Embedded statemachine dev
  .gitignore
  Makefile
  embedded/CMakeLists.txt
  embedded/README.md
  embedded/app/include/badgerloop.h
  embedded/app/include/state_machine.h
  embedded/app/main/main.cpp
  embedded/app/src/state_machine.c
  embedded/app/src/states.c
  embedded/app/src/transitions.c
  embedded/data/data.h
  embedded/data/readme.txt
  embedded/drivers/include/can.h
  embedded/drivers/src/can.c
  middleware/src/HVTCPSocket.cpp
  package-lock.json
Labels: Controls, big, important
